force-app/main/default/objects/Condition__c/Condition__c.object-meta.xml
<CustomObject>
    <label>Condition</label>
    <nameField>
        <label>Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF(
  AND(MONTH(TODAY()) &gt; MONTH(Birthdate), YEAR(TODAY()) &gt; YEAR(Birthdate))
  ,YEAR(TODAY()) - YEAR(Birthdate)
  ,IF(
    AND(MONTH(TODAY()) = MONTH(Birthdate), DAY(TODAY()) &gt;= DAY(Birthdate), YEAR(TODAY()) &gt; YEAR(Birthdate))
    ,YEAR(TODAY()) - YEAR(Birthdate)
    ,YEAR(TODAY()) - YEAR(Birthdate) - 1
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PossibleCondition__c/PossibleCondition__c.object-meta.xml
<CustomObject>
    <label>Possible Condition</label>
    <nameField>
        <displayFormat>PC-{0000}</displayFormat>
        <label>Possible Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Possible Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PossibleCondition__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Condition</label>
    <referenceTo>Condition__c</referenceTo>
    <relationshipLabel>Possible Conditions</relationshipLabel>
    <relationshipName>PossibleConditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PossibleCondition__c/fields/Probability__c.field-meta.xml
<CustomField>
    <fullName>Probability__c</fullName>
    <label>Probability</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Symptom__c/Symptom__c.object-meta.xml
<CustomObject>
    <label>Symptom</label>
    <nameField>
        <label>Symptom Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Symptoms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Symptom__c/fields/CommonName__c.field-meta.xml
<CustomField>
    <fullName>CommonName__c</fullName>
    <label>CommonName</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Symptom__c/fields/InfermedicaId__c.field-meta.xml
<CustomField>
    <fullName>InfermedicaId__c</fullName>
    <label>Infermedica Id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/SymptomExtension.cls
public class SymptomExtension {
	public List<Symptom__c> Symptoms { get; set; }
	public List<Map<String, String>> PresentingSymptoms { get; set; }
	public List<String> SelectedConditions { get; set; }
	public Contact UserContact { get; set; }

	public SymptomExtension() {
		Symptoms = [
			SELECT Present__c, CommonName__c, InfermedicaId__c, OwnerId 
			FROM Symptom__c
			LIMIT 1000
		];
		String userId = UserInfo.getUserId();
		UserContact = [
			SELECT Id, Name, Age__c, Sex__c
			FROM Contact
			WHERE Id IN(SELECT ContactId
			FROM User
			WHERE Id = :userId)
		];
	}

	public PageReference goToPossibleConditions() {
		String url = '/apex/ConditionChecker';
		Pagereference pageRef = new Pagereference(url);
		return pageRef;
	}

	public PageReference submitSymptoms() {
		presentingSymptoms = new List<Map<String, String>>();
		for (Symptom__c s :Symptoms) {
			if(s.Present__c == true) {
				Map<String, String> presenting = new Map<String, String>();
				presenting.put('id', s.InfermedicaId__c);
				presenting.put('choice_id', 'present');
				presentingSymptoms.add(presenting);
			}
		}
		ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO, 'Symptoms: ' + PresentingSymptoms);
		ApexPages.addMessage(myMsg);
		insertPossibleConditions();
		return goToPossibleConditions();
	}
	public void insertPossibleConditions() {

		try{
			APIInput a = new APIInput();
			a.sex = userContact.Sex__c.toLowerCase();
			a.age = String.valueOf(userContact.Age__c);
			a.evidence = presentingSymptoms;
			List<Object> conditions = InfermedicaTester.sendRequest(a, 'diagnosis');

			List<Map<String, Object>> conditionList = new List<Map<String, Object>>();
			List<PossibleCondition__c> newPossibleConditions = new List<PossibleCondition__c>();

			for (Object condition :conditions) {
				String s = JSON.serialize(condition);
				Map<String, Object> m = (Map<String, Object>) JSON.deserializeUntyped(s);
				conditionList.add(m);
			}
			List<Condition__c> newConditions = [
				SELECT Id, CommonName__c
				FROM Condition__c
			];

			for (Map<String, Object> condition :conditionList) {
				PossibleCondition__c p = new PossibleCondition__c();
				p.Probability__c = (Decimal) condition.get('probability');
				for (Condition__c c :newConditions) {
					if(condition.get('name') == c.CommonName__c)
						p.Condition__c = c.Id;
				}
				newPossibleConditions.add(p);
			}
			insert newPossibleConditions;
		} 
		catch(Exception ex) {
			ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO, ex.getMessage());
			ApexPages.addMessage(myMsg);
		}
	}

}