force-app/main/default/objects/Condition__c/Condition__c.object-meta.xml
<CustomObject>
    <label>Condition</label>
    <nameField>
        <label>Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PossibleCondition__c/PossibleCondition__c.object-meta.xml
<CustomObject>
    <label>Possible Condition</label>
    <nameField>
        <displayFormat>PC-{0000}</displayFormat>
        <label>Possible Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Possible Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PossibleCondition__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Condition</label>
    <referenceTo>Condition__c</referenceTo>
    <relationshipLabel>Possible Conditions</relationshipLabel>
    <relationshipName>PossibleConditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PossibleCondition__c/fields/Probability__c.field-meta.xml
<CustomField>
    <fullName>Probability__c</fullName>
    <label>Probability</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Specialty__c/Specialty__c.object-meta.xml
<CustomObject>
    <label>Specialty</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Specialty Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Specialties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Specialty__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Condition</label>
    <referenceTo>Condition__c</referenceTo>
    <relationshipLabel>Specialties</relationshipLabel>
    <relationshipName>Specialties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Specialty__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Doctor</label>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipLabel>Specialties</relationshipLabel>
    <relationshipName>Specialties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PossibleConditionExt.cls
public class PossibleConditionExt {
	public List<PossibleCondition__c> PossibleConditions { get; set; }
	public Contact userContact { get; set; }
	public List<String> SelectedConditions { get; set; }
	public List<Specialty__c> Specialties { get; set; }
	public List<SelectOption> options = new List<SelectOption>();

	public String selectedDoctor = null;
	public PossibleConditionExt() {
		String userId = UserInfo.getUserId();
		PossibleConditions = [SELECT
						      Selected__c, 
						      Condition__c, 
						      Probability__c
						      FROM
						      PossibleCondition__c
						      WHERE
						      OwnerId = :userId];

	}

	public List<SelectOption> getItems() {
		// //for (Specialty__c s : Specialties) {
		//     Integer i = 0;
		//     while(i < 5){
		//         options.add(new SelectOption('AAAAAAAa' + String.valueOf(i), 'AAAAAAAa' +  String.valueOf(i)));
		//         i += 1;
		//     }
		return options;
	}

	public String getSelectedDoctor() {
		return selectedDoctor;
	}
	public void setSelectedDoctor(String selectedDoctor) {
		this.selectedDoctor = selectedDoctor;
	}

	public void submitForDoctors() {
		//...
		SelectedConditions = new List<String>();
		// collect condition ids
		List<Id> idList = new List<Id>();

		for (PossibleCondition__c pCond :PossibleConditions) {
			if(pCond.Selected__c == true) {
				idList.add(pCond.Condition__c);
			}
		}
		Specialties = [SELECT
					   Doctor__r.Name, Condition__c
					   FROM
					   Specialty__c
					   WHERE
					   Condition__c IN :idList
		];
		Map<Id, String> condNamesMap = new Map<Id, String>();
		for (Condition__c cc :[SELECT Id, Name FROM Condition__c]) {
			if(!condNamesMap.containsKey(cc.Id)) {
				condNamesMap.put(cc.Id, cc.Name);
				}
		}


		Map<String, List<String>> doctorListOfConditions = new Map<String, List<String>>();
		for(Specialty__c sp :Specialties) {
			String docName = sp.Doctor__r.Name;
			String condName = condNamesMap.get(sp.Condition__c);

			if(doctorListOfConditions.containsKey(docName)) {
				doctorListOfConditions.get(docName).add(condName);
			} else {
				doctorListOfConditions.put(docName, new List<String>{condName});
			}
		}
		for(String key : doctorListOfConditions.keySet()) {
			String value = key + doctorListOfConditions.get(key);
			options.add(new SelectOption(key, value));
		}
	}
}