force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>Appt-{0000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Doctor</label>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Condition__c/Condition__c.object-meta.xml
<CustomObject>
    <label>Condition</label>
    <nameField>
        <label>Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Doctor__c/fields/DaysOpen__c.field-meta.xml
<CustomField>
    <fullName>DaysOpen__c</fullName>
    <label>DaysOpen</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/DurationHrs__c.field-meta.xml
<CustomField>
    <fullName>DurationHrs__c</fullName>
    <label>Duration(hrs)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/DurationMin__c.field-meta.xml
<CustomField>
    <fullName>DurationMin__c</fullName>
    <label>Duration(min)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/HourClose__c.field-meta.xml
<CustomField>
    <fullName>HourClose__c</fullName>
    <label>Hour Close</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/HourOpen__c.field-meta.xml
<CustomField>
    <fullName>HourOpen__c</fullName>
    <label>Hour Open</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PossibleCondition__c/PossibleCondition__c.object-meta.xml
<CustomObject>
    <label>Possible Condition</label>
    <nameField>
        <displayFormat>PC-{0000}</displayFormat>
        <label>Possible Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Possible Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PossibleCondition__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipLabel>Possible Conditions</relationshipLabel>
    <relationshipName>PossibleConditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PossibleCondition__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Condition</label>
    <referenceTo>Condition__c</referenceTo>
    <relationshipLabel>Possible Conditions</relationshipLabel>
    <relationshipName>PossibleConditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Specialty__c/Specialty__c.object-meta.xml
<CustomObject>
    <label>Specialty</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Specialty Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Specialties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Specialty__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Condition</label>
    <referenceTo>Condition__c</referenceTo>
    <relationshipLabel>Specialties</relationshipLabel>
    <relationshipName>Specialties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Specialty__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Doctor</label>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipLabel>Specialties</relationshipLabel>
    <relationshipName>Specialties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Symptom__c/Symptom__c.object-meta.xml
<CustomObject>
    <label>Symptom</label>
    <nameField>
        <label>Symptom Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Symptoms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DataCreator.cls
public class DataCreator {
    public static void createData() {
	    deleteExistingData();
        
        createAccount();
        createDoctors();
        createConditions();
         
        // Lookup(Doctor)
        // Lookup(Condition)
        createSpecialties();
    }
    
    private static void deleteExistingData() {
        deleteExistingPossibleConditions();
        deleteExistingAppointments();
        deleteExistingSpecialties();
        deleteExistingConditions();
        deleteExistingSymptoms();
        deleteExistingContacts();
        deleteExistingAccount();
        deleteExistingDoctors();
    }
    
    private static void deleteExistingSymptoms() { delete [SELECT Id FROM Symptom__c]; }
    private static void deleteExistingAccount() { delete [SELECT Id FROM Account]; }
    private static void deleteExistingContacts() { delete [SELECT Id FROM Contact]; }
    private static void deleteExistingAppointments() { delete [SELECT Id FROM Appointment__c]; }
    private static void deleteExistingDoctors() { delete [SELECT Id FROM Doctor__c]; }
    private static void deleteExistingSpecialties() { delete [SELECT Id FROM Specialty__c]; }
    private static void deleteExistingPossibleConditions() { delete [SELECT Id FROM PossibleCondition__c]; }
    private static void deleteExistingConditions() { delete [SELECT Id FROM Condition__c]; }
    
    private static void createAccount() {
        Account account = new Account(Name = 'Patient Account');
        insert account;
    }
    
    private static void createDoctors() {
        
        List<Doctor__c> doctors = new List<Doctor__c>();
        
        doctors.add(new Doctor__c(Birthdate__c = Date.newInstance(1998, 02, 22)
                   ,Sex__c = 'Male'
                   ,Name = 'Doctor Acula'
                   ,HourOpen__c = Time.newInstance(8, 0, 0, 0)
                   ,HourClose__c = Time.newInstance(17, 0, 0, 0)
                   ,Location__c = '123 Doc Street Reston, VA 20190'
                   ,DaysOpen__c = 'Monday;Wednesday;Friday'
                   ,DurationHrs__c = 2
                   ,DurationMin__c = 30));
        
        doctors.add(new Doctor__c(Birthdate__c = Date.newInstance(1970, 05, 17)
                   ,Sex__c = 'Female'
                   ,Name = 'Doctor Agon'
                   ,HourOpen__c = Time.newInstance(9, 0, 0, 0)
                   ,HourClose__c = Time.newInstance(16, 0, 0, 0)
                   ,Location__c = '999 Doctor Ave Billings, MT 59101'
                   ,DaysOpen__c = 'Monday;Tuesday;Wednesday;Thursday;Friday'
                   ,DurationHrs__c = 1
                   ,DurationMin__c = 15));
        
        doctors.add(new Doctor__c(Birthdate__c = Date.newInstance(1998, 02, 22)
                   ,Sex__c = 'Male'
                   ,Name = 'Medic Anne'
                   ,HourOpen__c = Time.newInstance(9, 30, 0, 0)
                   ,HourClose__c = Time.newInstance(18, 0, 0, 0)
                   ,Location__c = '123 Doc Street Reston, VA 20190'
                   ,DaysOpen__c = 'Sunday;Monday;Tuesday;Wednesday;Thursday'
                   ,DurationHrs__c = 0
                   ,DurationMin__c = 45));
        
        doctors.add(new Doctor__c(Birthdate__c = Date.newInstance(1961, 11, 29)
                   ,Sex__c = 'Female'
                   ,Name = 'Doctor Amatic'
                   ,HourOpen__c = Time.newInstance(6, 0, 0, 0)
                   ,HourClose__c = Time.newInstance(11, 30, 0, 0)
                   ,Location__c = '123 Doc Street Reston, VA 20190'
                   ,DaysOpen__c = 'Sunday;Monday;Wednesday;Friday;Saturday'
                   ,DurationHrs__c = 1
                   ,DurationMin__c = 45));
        
        insert doctors;
    }
    
    private static void createSpecialties() {
        
        List<Specialty__c> specialties = new List<Specialty__c>();
        List<Doctor__c> doctors = [SELECT Id FROM Doctor__c];
        List<Condition__c> conditions = [SELECT Id FROM Condition__c LIMIT 4];
        
        for (Integer i = 0; i < conditions.size(); ++i) {
            specialties.add(new Specialty__c(Doctor__c = doctors[i].Id
                                            ,Condition__c = conditions[i].Id));
        }
        insert specialties;
    }
}