force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>Appt-{0000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Condition__c/Condition__c.object-meta.xml
<CustomObject>
    <label>Condition</label>
    <nameField>
        <label>Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF(
  AND(MONTH(TODAY()) &gt; MONTH(Birthdate), YEAR(TODAY()) &gt; YEAR(Birthdate))
  ,YEAR(TODAY()) - YEAR(Birthdate)
  ,IF(
    AND(MONTH(TODAY()) = MONTH(Birthdate), DAY(TODAY()) &gt;= DAY(Birthdate), YEAR(TODAY()) &gt; YEAR(Birthdate))
    ,YEAR(TODAY()) - YEAR(Birthdate)
    ,YEAR(TODAY()) - YEAR(Birthdate) - 1
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PossibleCondition__c/PossibleCondition__c.object-meta.xml
<CustomObject>
    <label>Possible Condition</label>
    <nameField>
        <displayFormat>PC-{0000}</displayFormat>
        <label>Possible Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Possible Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PossibleCondition__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipLabel>Possible Conditions</relationshipLabel>
    <relationshipName>PossibleConditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PossibleCondition__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Condition</label>
    <referenceTo>Condition__c</referenceTo>
    <relationshipLabel>Possible Conditions</relationshipLabel>
    <relationshipName>PossibleConditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PossibleCondition__c/fields/Probability__c.field-meta.xml
<CustomField>
    <fullName>Probability__c</fullName>
    <label>Probability</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Specialty__c/Specialty__c.object-meta.xml
<CustomObject>
    <label>Specialty</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Specialty Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Specialties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Specialty__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Condition</label>
    <referenceTo>Condition__c</referenceTo>
    <relationshipLabel>Specialties</relationshipLabel>
    <relationshipName>Specialties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Symptom__c/Symptom__c.object-meta.xml
<CustomObject>
    <label>Symptom</label>
    <nameField>
        <label>Symptom Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Symptoms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Symptom__c/fields/InfermedicaId__c.field-meta.xml
<CustomField>
    <fullName>InfermedicaId__c</fullName>
    <label>Infermedica Id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/symptomExtension.cls
public class SymptomExtension {    
    public List<Symptom__c> Symptoms {get;set;}
    public List<Map<String, String>> PresentingSymptoms {get;set;}
    public List<Specialty__c> Specialties {get;set;}
    public List<PossibleCondition__c> PossibleConditions {get;set;}
    public List<String> SelectedConditions {get;set;}

    public Contact UserContact {get;set;}

    public SymptomExtension() {
        Symptoms = [SELECT Present__c, Name, InfermedicaId__c, OwnerId FROM Symptom__c];
        String userId = UserInfo.getUserId();
        if (userId.length() > 0) {
            UserContact = [
                SELECT Id, Name, Age__c, Sex__c
                FROM Contact
                WHERE Id IN (
                    SELECT ContactId
                    FROM User
                    WHERE Id = :userId
                )
            ];
        } else {
            UserContact.LastName = 'Unknown';
            UserContact.Birthdate = Date.parse('7/22/1995');
            UserContact.Sex__c = 'male';
        }
        PossibleConditions = [
            SELECT 
                Selected__c, 
                Condition__c, 
                Probability__c 
            FROM 
                PossibleCondition__c 
            WHERE 
                OwnerId =: userId 
                AND 
                Appointment__c != ''];
    }

    Integer count = 0;
    public Integer getCount() {return count;}
    public PageReference incrementCounter() {
            count++;
            return null;
    }

    // public List<PossibleCondition__c> getPossibleConditions(){
    //     return PossibleConditions;
    // }

    public void submitSymptoms() {
        presentingSymptoms = new List<Map<String, String>>();
        for (Symptom__c s : Symptoms) {
            if (s.Present__c == true) {
                Map<String, String> presenting = new Map<String, String>();
                presenting.put('id', s.InfermedicaId__c);
                presenting.put('choice_id', 'present');
                presentingSymptoms.add(presenting);
            }
        }
        insertPossibleConditions();
    }

 
    public void insertPossibleConditions() {
        APIInput a = new APIInput();
        a.sex = userContact.Sex__c.toLowerCase();
        a.age = String.valueOf(userContact.Age__c);
        a.evidence = presentingSymptoms;
        List<Object> conditions = InfermedicaTester.sendRequest(a);

        List<String> conditionNames = new List<String>();
        List<Map<String, Object>> conditionList = new List<Map<String, Object>>();
        List<PossibleCondition__c> newPossibleConditions = new List<PossibleCondition__c>();

        for (Object condition : conditions) {
            String s = JSON.serialize(condition);
            Map<String, Object> m = (Map<String, Object>)JSON.deserializeUntyped(s);
            conditionList.add(m);
            conditionNames.add((String)m.get('name'));
        }

        List<Condition__c> conditionRecords = [
            SELECT Id, Name 
            FROM Condition__c 
            WHERE Name 
            IN :conditionNames
        ];

        for (Map<String, Object> condition : conditionList) {
            PossibleCondition__c p = new PossibleCondition__c();
            p.Probability__c = (Decimal)condition.get('probability');
            for (Condition__c c : conditionRecords) {
                if (condition.get('name') == c.Name) p.Condition__c = c.Id;
            }
            newPossibleConditions.add(p);
        } insert newPossibleConditions;

    }
}