force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>Appt-{0000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Doctor</label>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Doctor__c/fields/DaysOpen__c.field-meta.xml
<CustomField>
    <fullName>DaysOpen__c</fullName>
    <label>DaysOpen</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/DurationHrs__c.field-meta.xml
<CustomField>
    <fullName>DurationHrs__c</fullName>
    <label>Duration(hrs)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/DurationMin__c.field-meta.xml
<CustomField>
    <fullName>DurationMin__c</fullName>
    <label>Duration(min)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/HourClose__c.field-meta.xml
<CustomField>
    <fullName>HourClose__c</fullName>
    <label>Hour Close</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/HourOpen__c.field-meta.xml
<CustomField>
    <fullName>HourOpen__c</fullName>
    <label>Hour Open</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/AppointmentCalendarController.cls
public with sharing class AppointmentCalendarController {

    public String doctor{get;set;}

    public String patient{get;set;}


    public AppointmentCalendarController(){
        doctor = ApexPages.currentPage().getParameters().get('docId');
        patient = ApexPages.currentPage().getParameters().get('patId');
    }

    public PageReference redirectToHome(){
        PageReference pageRef = new PageReference('/apex/HomePage?id='+patient);
        return pageRef;
    }

    @RemoteAction
    public static void createAppointment(Integer year, Integer month, Integer day, List<Integer> startTime, String doctorId, String patientId){
        Appointment__c appointment = new Appointment__c();
        appointment.Doctor__c = doctorId;
        appointment.Contact__c = patientId;
        appointment.Date__c = Date.newInstance(year, month, day);
        appointment.StartTime__c = Time.newInstance(startTime[0], startTime[1],0,0);
        try{
            insert appointment;
        } catch(Exception e){
        }
    }

    @RemoteAction
    public static Map<String, Object> getDoctorAndPatientInfo(String doctorId, String patientId){
        Doctor__c doc = [SELECT Id, Name, Location__c, HourClose__c, HourOpen__c, DaysOpen__c, DurationMin__c, DurationHrs__c
                        FROM Doctor__c WHERE Id =: doctorId];
        Contact patient = [SELECT Id, Name FROM Contact WHERE Id =: patientId];
        Map<String, Object> doctorAndPatientInfo = new Map<String, Object>();
        doctorAndPatientInfo.put('startTime', doc.HourOpen__c);
        doctorAndPatientInfo.put('endTime', doc.HourClose__c);
        doctorAndPatientInfo.put('doctorName', doc.Name);
        doctorAndPatientInfo.put('doctorAddress', doc.Location__c);
        doctorAndPatientInfo.put('daysOpen', doc.DaysOpen__c);
        doctorAndPatientInfo.put('durationHours', doc.DurationHrs__c);
        doctorAndPatientInfo.put('durationMinutes', doc.DurationMin__c);
        doctorAndPatientInfo.put('patientName', patient.Name);
        return doctorAndPatientInfo;
    }

    @RemoteAction
    public static Map<String, Object> getAppointmentInfo(String doctorId){
        List<Appointment__c> existingAppointments = [SELECT Doctor__r.Id, Contact__r.Name, Date__c, StartTime__c 
                                                    FROM Appointment__c 
                                                    WHERE Doctor__r.Id =: doctorId
                                                    AND Date__c != NULL
                                                    AND StartTime__c != NULL
                                                    ORDER BY Date__c];
        Map<String, Object> appointmentInfo = new Map<String, Object>();
        List<String> appointmentStrings = new List<String>();
        String dateFormat;
        Double minutes;
        for(Appointment__c app: existingAppointments){
            minutes = app.StartTime__c.minute()/60.0;
            dateFormat = app.Date__c.year() + ',' + app.Date__c.month() + ',' + app.Date__c.day() + ',' + (app.StartTime__c.hour() + minutes);
            appointmentStrings.add(dateFormat);
        }
        appointmentInfo.put('existingAppointments', appointmentStrings);
        return appointmentInfo;
    }
}