force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>Appt-{0000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancelled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Doctor</label>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF(
  AND(MONTH(TODAY()) &gt; MONTH(Birthdate), YEAR(TODAY()) &gt; YEAR(Birthdate))
  ,YEAR(TODAY()) - YEAR(Birthdate)
  ,IF(
    AND(MONTH(TODAY()) = MONTH(Birthdate), DAY(TODAY()) &gt;= DAY(Birthdate), YEAR(TODAY()) &gt; YEAR(Birthdate))
    ,YEAR(TODAY()) - YEAR(Birthdate)
    ,YEAR(TODAY()) - YEAR(Birthdate) - 1
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Doctor__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF(
  AND(MONTH(TODAY()) &gt; MONTH(Birthdate__c), YEAR(TODAY()) &gt; YEAR(Birthdate__c))
  ,YEAR(TODAY()) - YEAR(Birthdate__c)
  ,IF(
    AND(MONTH(TODAY()) = MONTH(Birthdate__c), DAY(TODAY()) &gt;= DAY(Birthdate__c), YEAR(TODAY()) &gt; YEAR(Birthdate__c))
    ,YEAR(TODAY()) - YEAR(Birthdate__c)
    ,YEAR(TODAY()) - YEAR(Birthdate__c) - 1
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HomePageController.cls
public with sharing class HomePageController {

    private List<Appointment__c> pastAppointments;
    private List<Appointment__c> futureAppointments;

    // Parameter to pass to appointment wizard URL
    public String idParam {get;set;}

    // User info
    private String userId;
    private List<Contact> userContact;

    // Get the current time and date in order to display 
    // past/future appointments scheduled for today, along with 
    // info messages
    private Datetime now = Datetime.now();

    private Integer years = now.year();
    private Integer months = now.month();
    private Integer days = now.day();
    private Date today = Date.newInstance(years, months, days);

    private Integer hours = now.hour();
    private Integer minutes = now.minute();
    private Integer seconds = now.second();
    private Time currentTime = Time.newInstance(hours, minutes, seconds, 0);

    public HomePageController() {

        userId = UserInfo.getUserId();
        userContact = [
            SELECT 
                Id
                ,Name
                ,Age__c
                ,Sex__c
            FROM Contact
            WHERE Id IN (
                SELECT ContactId
                FROM User
                WHERE Id = :userId
            )
            LIMIT 1
        ];

        pastAppointments = [
            SELECT 
                Id 
                ,Date__c 
                ,StartTime__c 
                ,Location__c 
                ,Doctor__c 
                ,Doctor__r.Name
                ,Contact__c
                ,Contact__r.FirstName
                ,Contact__r.LastName
                ,Cancelled__c
            FROM Appointment__c 
            WHERE (Contact__c =: userContact[0].Id) 
                AND ((Date__c < TODAY) 
                OR (Date__c = TODAY AND StartTime__c <: currentTime))
        ];

        futureAppointments = [
            SELECT 
                Id 
                ,Date__c 
                ,StartTime__c 
                ,Location__c 
                ,Doctor__c 
                ,Doctor__r.Name
                ,Contact__c
                ,Contact__r.FirstName
                ,Contact__r.LastName
                ,Cancelled__c
            FROM Appointment__c 
            WHERE (Contact__c =: userContact[0].Id) 
                AND ((Date__c > TODAY)
                OR (Date__c = TODAY AND StartTime__c >: currentTime))
        ];
    }

    public List<Appointment__c> getPastAppointments() {  
        for (Appointment__c appointment : pastAppointments) {
            if (appointment.Date__c == today) {
                ApexPages.addMessage(new ApexPages.Message(
                    ApexPages.Severity.INFO, 'You had an appointment today.')); 
                break;
            }
        }       
        return pastAppointments;
    }

    public List<Appointment__c> getFutureAppointments() {
        for (Appointment__c appointment : futureAppointments) {
            if (appointment.Date__c == today) {
                ApexPages.addMessage(new ApexPages.Message(
                    ApexPages.Severity.INFO, 'You have an appointment today.')); 
                break;
            }
        }    
        return futureAppointments;
    }

    public PageReference goToAppointmentWizard() {
        idParam = (String)userContact[0].Id;
        String url = '/apex/SymptomsChecker?id=' + idParam;
        Pagereference pageRef = new Pagereference(url);
        return pageRef;
    }
}